name: 'Patch Kernel for no-kprobe.'

runs:
  using: 'composite'
  steps:
      - name: Patch Kernel for no-kprobe
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          # Detect SuSFS is used to enable the SuSFS inline hook
          if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]] && [[ "${{ env.KERNELSU_AUTO_FORK }}" != "next" ]]; then
              bash susfs_inline_hook_patches.sh ./
              echo "[+] executed SuSFS inline hook successfully."
              if [[ "${{ env.HIDE_STUFF }}" != "true" ]]; then
                  bash backport_selinux_patches.sh
                  echo "[+] Patched SELinux."
              fi
          elif [[ "${{ env.HOOK_METHOD }}" == "syscall" ]] || \
               ( [[ "${{ env.SUSFS_ENABLE }}" == "true" ]] && [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]] ); then
              bash syscall_hook_patches.sh ./
              echo "[+] executed syscall hook successfully."
              if [[ "${{ env.HIDE_STUFF }}" != "true" ]]; then
                  bash backport_selinux_patches.sh
                  echo "[+] Patched SELinux."
              fi
          else
              echo "[-] please input a vaild option!"
              false
          fi
