name: Build Mi 9T Kernel

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "Mi_9T"
  DEVICE_CODENAME : "davinci"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/diquesg/android_kernel_xiaomi_sm6150.git"
  KERNEL_BRANCH : "sixteen-qpr2"

  CLANG_SOURCE : "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : ""
  GCC_64_BRANCH : ""
  GCC_32_SOURCE : ""
  GCC_32_BRANCH : ""

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "davinci_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "next"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "PixelOS_A16"

  # Other env
  PYTHON_VERSION: "3"

  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"

  KERNELSU_METHOD: "shell"

  # 🟢 SEUS PATCHES LEGÍTIMOS DO NEXT CONFIRMADOS AQUI
  PATCHES_SOURCE: "diquesg/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "mi_kernel"

  # 🟢 DEIXE EM BRANCO PARA O COMANDO "CP" LER DIRETO DA RAIZ DA SUA BRANCH SEM INVENTAR SUBPASTAS
  SUSFS_FOLDER_FIXED: 
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "false"

  HOOK_METHOD: "syscall"

  KERNEL_PATCH: "false"

  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: ""

  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  HIDE_STUFF: "false"

  GENERATE_DTB: "true"
  GENERATE_CHIP: "qcom"

  BUILD_DEBUGGER: "true"
  
  # 🟢 DEIXE EM TRUE PARA O ROBÔ LIMPAR OS REJEITOS DE LINHA DO CMDLINE E AVANÇAR O BUILD
  SKIP_PATCH: "true"

  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""
  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v6

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get necessary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          # 1. Ativar as camadas virtuais que a sua ROM exige
          echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/davinci_defconfig
          echo "CONFIG_KSU_DEBUG=y" >> arch/arm64/configs/davinci_defconfig
          
          # 2. Forçar as SEPolicies do Next direto no Makefile do driver clonado
          echo "HAVE_KSU_HOOK := 0" >> drivers/kernelsu/Kbuild
          echo "ccflags-y += -DCONFIG_KSU_MANUAL_HOOK -DKSU_HAVE_HOOK -DCONFIG_KSU_NEXT" >> drivers/kernelsu/Kbuild

          # 🟢 APROVEITAR APENAS O COMANDO UNIVERSAL DE LIMPEZA DE MEMÓRIA (SEGURO E ISOLADO):
          sed -i '/#ifdef CONFIG_KSU_SUSFS/,/#endif/d' fs/dcache.c

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
